// Pure config.toml builder for the V3 setup wizard.
//
// Lives on the renderer side so the wizard can preview the document
// before asking Electron to write it. Matches the schema enforced by
// `apps/server/src/config/serverNodeConfig.ts` (sections `[server]`,
// `[auth]`, `[database]`, `[cloud_env]`, `[limits]`) from master plan
// §10.4. Intentionally hand-rolled — smol-toml's encoder is available
// server-side but pulling it into the web bundle would balloon the
// client payload for a one-shot flow.
//
// Sections are emitted only when at least one field is populated, so a
// minimal wizard run produces a clean, readable file with no empty
// `[limits]` noise.

import type { V3SetupWizardState } from "./state";

const escapeString = (value: string): string => {
  // TOML basic strings accept most characters but require escaping for
  // the double quote + backslash + control chars.
  return value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
};

const emitString = (key: string, value: string | null | undefined): string | null =>
  value === null || value === undefined || value.length === 0
    ? null
    : `${key} = "${escapeString(value)}"`;

const emitInt = (key: string, value: number | null | undefined): string | null =>
  value === null || value === undefined ? null : `${key} = ${Math.trunc(value)}`;

const emitStringArray = (
  key: string,
  values: ReadonlyArray<string> | null | undefined,
): string | null => {
  if (values === null || values === undefined || values.length === 0) return null;
  const inner = values.map((v) => `"${escapeString(v)}"`).join(", ");
  return `${key} = [${inner}]`;
};

const joinSection = (header: string, entries: ReadonlyArray<string | null>): string | null => {
  const body = entries.filter((e): e is string => e !== null);
  if (body.length === 0) return null;
  return [`[${header}]`, ...body].join("\n");
};

export interface BuildTomlOptions {
  // A header comment helps operators understand what produced this file
  // and makes in-place edits less dangerous. Optional so tests can
  // produce deterministic, byte-for-byte output.
  readonly header?: string | null;
}

export const buildServerNodeConfigToml = (
  state: V3SetupWizardState,
  options: BuildTomlOptions = {},
): string => {
  const authorizedEmails = state.auth.authorizedEmails
    .split(/[\s,]+/)
    .map((entry) => entry.trim().toLowerCase())
    .filter((entry) => entry.length > 0);

  const sections = [
    joinSection("server", [
      emitString("public_url", state.exposure.publicUrl),
      emitString("bind_host", state.exposure.bindHost),
      emitInt("bind_port", state.exposure.bindPort),
    ]),
    joinSection("auth", [
      emitString("google_client_id", state.auth.googleClientId),
      emitStringArray("authorized_emails", authorizedEmails),
    ]),
    joinSection("database", [
      emitString("postgres_url", state.database.postgresUrl),
      emitString("encryption_key", state.database.encryptionKey),
    ]),
  ].filter((section): section is string => section !== null);

  const header =
    options.header === null
      ? null
      : (options.header ??
        [
          "# V3 Code server-node configuration.",
          "# Generated by the setup wizard; hand-edit carefully.",
          "# Docs: https://github.com/aGamingGod1234/v3code",
        ].join("\n"));

  const parts = [header, ...sections].filter((p): p is string => p !== null);
  return parts.join("\n\n") + "\n";
};
