// V3 device identity persistence (renderer-side).
//
// Each V3 client device has a stable UUID generated on first launch and
// persisted across sessions. This is the `device_id` end of the V3 mesh's
// device model — it's how the server distinguishes "this device, returning"
// from "a brand-new device that needs approval" (spec §3.3).
//
// Storage: `localStorage`. The id is non-sensitive (it's just an opaque
// random UUID; the server never trusts it without a valid Google ID token
// proving the user is authorised). On Electron we still use localStorage —
// `safeStorage` is reserved for credentials. On browser-only deployments,
// localStorage is the only option that survives a tab refresh.
//
// Resilience: a missing or malformed entry triggers regeneration rather
// than throwing. A regenerated id will look like a fresh device to the
// server, which is the correct behaviour after `localStorage` is cleared.

import { DeviceId } from "@v3tools/contracts";

const STORAGE_KEY = "v3.device-id";

const isDeviceIdShape = (value: string): boolean =>
  // UUID v4 textual form, lowercase. Generated by `crypto.randomUUID()`.
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(value);

const safeRead = (): string | null => {
  try {
    return window.localStorage.getItem(STORAGE_KEY);
  } catch {
    return null;
  }
};

const safeWrite = (value: string): void => {
  try {
    window.localStorage.setItem(STORAGE_KEY, value);
  } catch {
    // Quota exceeded or storage disabled (private mode in some browsers).
    // Returning silently means the renderer regenerates an id every load,
    // which the server-side device approval flow handles gracefully.
  }
};

const mintDeviceId = (): string => {
  if (typeof globalThis.crypto?.randomUUID === "function") {
    return globalThis.crypto.randomUUID();
  }
  // Pre-Node-18 / very old browser fallback. We are on React 19 + modern
  // Electron in V3, so this branch is essentially dead code, but keeping
  // it documents intent and avoids a hard crash on a broken host.
  const bytes = new Uint8Array(16);
  globalThis.crypto.getRandomValues(bytes);
  bytes[6] = (bytes[6]! & 0x0f) | 0x40;
  bytes[8] = (bytes[8]! & 0x3f) | 0x80;
  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20, 32)}`;
};

export const resolveDeviceId = (): DeviceId => {
  const existing = safeRead();
  if (existing !== null && isDeviceIdShape(existing)) {
    return DeviceId.make(existing);
  }
  const minted = mintDeviceId();
  safeWrite(minted);
  return DeviceId.make(minted);
};

// Test seam: lets a unit test snapshot then restore a clean storage state.
export const __resetDeviceIdForTests = (): void => {
  try {
    window.localStorage.removeItem(STORAGE_KEY);
  } catch {
    // ignore
  }
};
