/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairRouteImport } from './routes/pair'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ControlRouteImport } from './routes/control'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsWorktreesRouteImport } from './routes/settings.worktrees'
import { Route as SettingsUsageRouteImport } from './routes/settings.usage'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsPersonalizationRouteImport } from './routes/settings.personalization'
import { Route as SettingsMcpRouteImport } from './routes/settings.mcp'
import { Route as SettingsGitRouteImport } from './routes/settings.git'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsEnvironmentsRouteImport } from './routes/settings.environments'
import { Route as SettingsDevicesRouteImport } from './routes/settings.devices'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsConfigurationRouteImport } from './routes/settings.configuration'
import { Route as SettingsBrowserRouteImport } from './routes/settings.browser'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsWorktreesRoute = SettingsWorktreesRouteImport.update({
  id: '/worktrees',
  path: '/worktrees',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsageRoute = SettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPersonalizationRoute = SettingsPersonalizationRouteImport.update({
  id: '/personalization',
  path: '/personalization',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMcpRoute = SettingsMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGitRoute = SettingsGitRouteImport.update({
  id: '/git',
  path: '/git',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEnvironmentsRoute = SettingsEnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDevicesRoute = SettingsDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConfigurationRoute = SettingsConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBrowserRoute = SettingsBrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/admin': typeof AdminRoute
  '/control': typeof ControlRoute
  '/login': typeof LoginRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/configuration': typeof SettingsConfigurationRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/environments': typeof SettingsEnvironmentsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/git': typeof SettingsGitRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/personalization': typeof SettingsPersonalizationRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/settings/worktrees': typeof SettingsWorktreesRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/control': typeof ControlRoute
  '/login': typeof LoginRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/configuration': typeof SettingsConfigurationRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/environments': typeof SettingsEnvironmentsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/git': typeof SettingsGitRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/personalization': typeof SettingsPersonalizationRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/settings/worktrees': typeof SettingsWorktreesRoute
  '/': typeof ChatIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/admin': typeof AdminRoute
  '/control': typeof ControlRoute
  '/login': typeof LoginRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/browser': typeof SettingsBrowserRoute
  '/settings/configuration': typeof SettingsConfigurationRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/devices': typeof SettingsDevicesRoute
  '/settings/environments': typeof SettingsEnvironmentsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/git': typeof SettingsGitRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/personalization': typeof SettingsPersonalizationRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/settings/worktrees': typeof SettingsWorktreesRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/control'
    | '/login'
    | '/pair'
    | '/settings'
    | '/setup'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/browser'
    | '/settings/configuration'
    | '/settings/connections'
    | '/settings/devices'
    | '/settings/environments'
    | '/settings/general'
    | '/settings/git'
    | '/settings/mcp'
    | '/settings/personalization'
    | '/settings/providers'
    | '/settings/usage'
    | '/settings/worktrees'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/control'
    | '/login'
    | '/pair'
    | '/settings'
    | '/setup'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/browser'
    | '/settings/configuration'
    | '/settings/connections'
    | '/settings/devices'
    | '/settings/environments'
    | '/settings/general'
    | '/settings/git'
    | '/settings/mcp'
    | '/settings/personalization'
    | '/settings/providers'
    | '/settings/usage'
    | '/settings/worktrees'
    | '/'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
  id:
    | '__root__'
    | '/_chat'
    | '/admin'
    | '/control'
    | '/login'
    | '/pair'
    | '/settings'
    | '/setup'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/browser'
    | '/settings/configuration'
    | '/settings/connections'
    | '/settings/devices'
    | '/settings/environments'
    | '/settings/general'
    | '/settings/git'
    | '/settings/mcp'
    | '/settings/personalization'
    | '/settings/providers'
    | '/settings/usage'
    | '/settings/worktrees'
    | '/_chat/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  AdminRoute: typeof AdminRoute
  ControlRoute: typeof ControlRoute
  LoginRoute: typeof LoginRoute
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/worktrees': {
      id: '/settings/worktrees'
      path: '/worktrees'
      fullPath: '/settings/worktrees'
      preLoaderRoute: typeof SettingsWorktreesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/usage': {
      id: '/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof SettingsUsageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/personalization': {
      id: '/settings/personalization'
      path: '/personalization'
      fullPath: '/settings/personalization'
      preLoaderRoute: typeof SettingsPersonalizationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/mcp': {
      id: '/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof SettingsMcpRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/git': {
      id: '/settings/git'
      path: '/git'
      fullPath: '/settings/git'
      preLoaderRoute: typeof SettingsGitRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/environments': {
      id: '/settings/environments'
      path: '/environments'
      fullPath: '/settings/environments'
      preLoaderRoute: typeof SettingsEnvironmentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/devices': {
      id: '/settings/devices'
      path: '/devices'
      fullPath: '/settings/devices'
      preLoaderRoute: typeof SettingsDevicesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/configuration': {
      id: '/settings/configuration'
      path: '/configuration'
      fullPath: '/settings/configuration'
      preLoaderRoute: typeof SettingsConfigurationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/browser': {
      id: '/settings/browser'
      path: '/browser'
      fullPath: '/settings/browser'
      preLoaderRoute: typeof SettingsBrowserRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsBrowserRoute: typeof SettingsBrowserRoute
  SettingsConfigurationRoute: typeof SettingsConfigurationRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsDevicesRoute: typeof SettingsDevicesRoute
  SettingsEnvironmentsRoute: typeof SettingsEnvironmentsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsGitRoute: typeof SettingsGitRoute
  SettingsMcpRoute: typeof SettingsMcpRoute
  SettingsPersonalizationRoute: typeof SettingsPersonalizationRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsUsageRoute: typeof SettingsUsageRoute
  SettingsWorktreesRoute: typeof SettingsWorktreesRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsBrowserRoute: SettingsBrowserRoute,
  SettingsConfigurationRoute: SettingsConfigurationRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsDevicesRoute: SettingsDevicesRoute,
  SettingsEnvironmentsRoute: SettingsEnvironmentsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsGitRoute: SettingsGitRoute,
  SettingsMcpRoute: SettingsMcpRoute,
  SettingsPersonalizationRoute: SettingsPersonalizationRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsUsageRoute: SettingsUsageRoute,
  SettingsWorktreesRoute: SettingsWorktreesRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  AdminRoute: AdminRoute,
  ControlRoute: ControlRoute,
  LoginRoute: LoginRoute,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
